{"name": "test_msi_login", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message:", "trace": "self = <scripts.test03_msi_login.TestMsiLogin object at 0x00000203C05FD040>\nusername = 'testid', pwd = 'testpwd123'\n\n    def test_msi_login(self, username='testid', pwd= 'testpwd123'):\n        sleep(1)\n>       self.msi.page_msi_login(username,pwd)\n\ntest03_msi_login.py:22: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n..\\page\\page_msi_login.py:28: in page_msi_login\n    self.page_click_longinButton()\n..\\page\\page_msi_login.py:20: in page_click_longinButton\n    self.base_click(page.msi_login_btn)\n..\\base\\base.py:41: in base_click\n    ele = self.base_find(loc)\n..\\base\\base.py:24: in base_find\n    return (WebDriverWait(self.driver,\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"6842bca3d4fc7426eae74fd225fce991\")>\nmethod = <function Base.base_find.<locals>.<lambda> at 0x00000203C09D40D0>\nmessage = ''\n\n    def until(self, method, message=''):\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value is not False.\"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.time() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, 'screen', None)\n                stacktrace = getattr(exc, 'stacktrace', None)\n            time.sleep(self._poll)\n            if time.time() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message:\n\nC:\\Users\\45464\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py:80: TimeoutException"}, "attachments": [{"name": "log", "source": "ccf35311-34d5-42f0-9122-b3a3ab981c9a-attachment.txt", "type": "text/plain"}], "start": 1605974555300, "stop": 1605974616798, "uuid": "65843183-f677-44c8-bce9-13e78856e623", "historyId": "35d4f0141b46e59a7d0cbfb569a805ee", "testCaseId": "8ba2bfd2358a144f1645a92d9ebc5c16", "fullName": "scripts.test03_msi_login.TestMsiLogin#test_msi_login", "labels": [{"name": "parentSuite", "value": "scripts"}, {"name": "suite", "value": "test03_msi_login"}, {"name": "subSuite", "value": "TestMsiLogin"}, {"name": "host", "value": "DESKTOP-41H0IB1"}, {"name": "thread", "value": "14008-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scripts.test03_msi_login"}]}